### ISSUE TITLE
Can you make your bootstrap to be npm package?

### ISSUE THREAD

**Issue by ggrnd0** [TwanoO67/ng2-admin-lte#34]
Can you make your bootstrap to be npm package?

**Comment by TwanoO67** [comment]
Hello,

It could be really cool, but I don't know how to do that, because the "bootstraping" files couldn't be in a vendor folder.

One thing that we could do is a npm package with a bin that generate those files ( or move them from the node_modules to the actual folder).
And that seems a little pointless because it will still overwrite the content generated by ng-cli

And otherthing could be to have a script, doing all the modification that I did to the bootstraping files, over à fresh ng-cli install.
It's the only way I see that would be usefull ( because you will be able to start that script another time if you have an upgrade) 
But it really will be really à lot of work to do that, and it will require constant update to match with the ng-cli file.

But if you have an idea on that, or want to make a first version, I'm open to it.

A good exemple of a file to handle would be "Angular-cli.json". How could we make a script that modify the content of this file coming from "ng new" ? When we dont know the version of ng-cli running

**Comment by ggrnd0** [comment]
> A good exemple of a file to handle would be "angular-cli.json". How could we make a script that modify the content of this file coming from "ng new" ? When we dont know the version of ng-cli running

what to modify?

**Comment by TwanoO67** [comment]
all the angular-cli.json content.
like the array of assets or style.

How could you import that in a npm package ?

**Comment by TwanoO67** [comment]
I don't think it's possible to do that at the moment...

**Comment by ggrnd0** [comment]
> all the angular-cli.json content.
> like the array of assets or style.

> How could you import that in a npm package ?

I dont think it is critical.
angular-cli.json can be checked with orig in this repo manually after something fails.
But now users need copy bootstrap for update...

updating with npm will be easier.

**Comment by TwanoO67** [comment]
If you have any idea on how to do implement that,  feel free to do a PR. 
Because I dont know...
