### ISSUE TITLE
angular-cli github-pages deploy

### ISSUE THREAD

**Issue by cindoum** [TwanoO67/ng2-admin-lte#36]
Hi,

Did you manage to have a github-pages working with your app using `ng github-pages:deploy --user-page --message "Optional commit message"` ?

When i try the page get created but the app is just not working at all... 

See [this page](https://cindoum.github.io/ng2lte/)

Thanks

**Comment by TwanoO67** [comment]
Hello,

It's working well ( at least since I updated to full node_modules assets)
See here: https://twanoo67.github.io/ng2-admin-lte/ 
but you have to modify the index.html to set the base href to your repo name.
So for me it was "/ng2-admin-lte/"
And of course you have to update your auth0 account to set the callback url right
