### ISSUE TITLE
How can I fix heigth of main screen after loading?

### ISSUE THREAD

**Issue by boskiv** [TwanoO67/ng2-admin-lte#60]
![screenshot from 2016-12-26 13-22-23](https://cloud.githubusercontent.com/assets/1939783/21481278/8263e1fc-cb6e-11e6-900b-eeaaf9e6a6dd.png)

**Comment by boskiv** [comment]
when I checkout and then check in  on `height:100% ` in browser inspection, it fit right.

**Comment by TwanoO67** [comment]
Yep I see the problem too, but I don't know where the problem is.

Normally the javascript of AdminLTE would react to the resize of the page, but with angular, there's resizing that don't "pop" these event.
So to fix that, I simulate a resize event, with that line 35 ( https://github.com/TwanoO67/ng2-admin-lte/blob/master/src/app/app.component.ts )
It was well working, but since we have the authO connection i'ts not working anymore.
I suppose that those event triggering should be called later in the loading, but I don't know where at the moment

**Comment by TwanoO67** [comment]
Seems fixed since the removal of Auth0 login
