### ISSUE TITLE
Duplicate empty card when create client

### ISSUE THREAD

**Issue by boskiv** [TwanoO67/ng2-admin-lte#61]
When I create client, I have see duplicate card displayed in view with same ID but empty fields.
![screenshot from 2016-12-26 17-58-44](https://cloud.githubusercontent.com/assets/1939783/21484055/36691e58-cb95-11e6-93a6-dad310017451.png)

If I click to delete it it removes both of them. Cause IDs is same.

**Comment by boskiv** [comment]
In firebase database I see
![screenshot from 2016-12-26 18-32-17](https://cloud.githubusercontent.com/assets/1939783/21484343/ae9ba8ce-cb99-11e6-9165-b89c966d0705.png)

**Comment by TwanoO67** [comment]
Sorry I can't help I don't use firebase at all 
(it was a PR by @cindoum )

But as I see here line 11: https://github.com/TwanoO67/ng2-admin-lte/blame/master/src/app/dal/client.dal.ts

the readAll function is an Observable.
So instead of the async pipe, you could use a subscribe.

In line 21 in file https://github.com/TwanoO67/ng2-admin-lte/blob/master/src/app/pages/client/client.component.ts

you could do something like:

this.dal.readAll().subscribe((data)=>{
console.log(data);
this.clients = data;
});

And in line 7 of this file: https://github.com/TwanoO67/ng2-admin-lte/blob/master/src/app/pages/client/client.component.html
remove the async pipe

Maybe it's helping...

**Comment by TwanoO67** [comment]
How is it working @boskiv ?
